### ISSUE TITLE
Why deal with left and right tables?

### ISSUE THREAD

**Issue by OlivierBinette** [NickCrews/mismo#20]
I'm not sure why record linkage is often stated as trying to link two different databases, unless we're in the realms of bipartite record linkage or one-to-many linkage.

The most general setup is to have a single table that we're trying to deduplicate. You can have any number of tables and stack them together.

Bipartite record linkage or one-to-many linkage can also be stated as a particular case of this, using a specific column to define data source origin and then to implement constraints based on that.

I think the clustering (or microclustering) point of view on entity resolution is the most flexible and modern.

**Comment by NickCrews** [comment]
Note that splink does this, the concatting into one table, with a "dataset_id" column for each record.

My original reasoning was that I was dealing with two datasets with different schemas, eg "donations" gave to "politicians", or "organizations/PACS" gave "donations". So these two different kinds of entities have different schemas, so concating into one table didn't make sense or work.

But, I can really see the benefit of
1. requiring users to unify the schemas
2. concatting into a single dataset
3. imposing comparison/clustering restrictions such as 1:M, M:M, etc between each dataset at later stages.

For example, in our call yesterday, say A and B are donations, and X is a politician. If our comparisons say that AX and BX are both matches, then we have to decide if A and B are the same donation. It would be great if we had some info on the AB pair to make that decision. But currently, mismo only makes inter-dataset comparisons, not intra-dataset comparisons, so we never even consider AB. Requiring a big concatted table would make this easier. But still, in the comparisons, I think we would need to have some ifelse code like

```python
is_dd = (dataset_id_l == "donations") & (dataset_id_l == "donations")
is_pp = (dataset_id_l == "politicians") & (dataset_id_l == "politicians")
return (
    ibis.case()
    .when(is_dd, <dd comparison logic>)
    .when(is_pp, <pp comparison logic>)
    .else_(<pd comparison logic>)
    .end()
)
```
so I'm not sure if we are reducing the problem, or just moving it around? I think the path forward I would like would be to add some benchmarks and other examples that have a variety of linkage constraints (dedupe 1 dataset, 1:1 link two datasets, 1:m link two datasets, etc) and just get a feel for how the API is now, and then we can imagine what it would be like with teh concatted model.

I'm thinking about this now, and maybe see a  If we want to compare entities of different schemas X and Y, do we need to define three different comparison models? XY, XX, and YY? Then, during clustering, we also would probably want to distinguish between these different kinds of comparisons. It seems like if we wanted to be really refined, then we should indeed do this. This seems like a lot of work though :( Now imagine 3 different schemas, all of a sudden you need 6 (XX YY ZZ XZ XY YZ)  different comparison models....

Thoughts?

**Comment by OlivierBinette** [comment]
I see your point. I think the comparison logic can simplify itself automatically by using NA values, i.e. comparison where one of the field is NA is just not taken into account. And then the linkage model can weight things differently depending on features such as `is_dd`.

But ultimately I think the most important thing is to have a user-friendly interface and in your use case having two tables is the most natural thing. As long as there's the option for a single table as well it should be good.

**Comment by NickCrews** [comment]
Sounds good. Just as a note, the [python dedupe library](https://docs.dedupe.io/en/latest/Variable-definition.html#missing-data) actually uses missing values as a signal, so we should look more into whether/how we should use nullness as a feature.

**Comment by OlivierBinette** [comment]
Good point!
